# Generated by Django 5.1.3 on 2024-12-04 21:22

import compressed_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default_profile.jpg', null=True, quality=60, upload_to='profiles'),
        ),
    ]
