# Generated by Django 5.1.3 on 2025-01-24 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.review'),
        ),
    ]
